version: '3.8'

services:
  petproject:
    build:
      context: ./petproject
      dockerfile: Dockerfile
    container_name: petproject
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./petproject:/usr/src/app
    working_dir: /usr/src/app
    stdin_open: true
    tty: true
    command: [ "yarn", "start" ]
    networks:
      - pet_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    env_file:
      - .env
    ports:
      - "80:80"
    networks:
      - pet_network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - petproject
      - geoserver
  
  postgis:
    image: postgis/postgis:latest
    container_name: postgis_db
    env_file:
      - .env
    networks:
      - pet_network

  geoserver:
    image: kartoza/geoserver:latest
    container_name: geoserver
    ports:
      - "8080:8080"
    env_file:
      .env
    depends_on:
      - postgis
    networks:
      - pet_network

volumes:
   geoserver-data:
   geo-db-data:


networks:
  pet_network:
    driver: bridge
