version: '3.8'

services:
  petproject:
    build:
      context: ./petproject
      dockerfile: Dockerfile
    container_name: petproject
    ports:
      - "3000:3000"
    volumes:
      - ./petproject:/usr/src/app
    working_dir: /usr/src/app
    stdin_open: true
    tty: true
    command: [ "yarn", "start" ]
    networks:
      - pet_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    networks:
      - pet_network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - petproject
  
  

networks:
  pet_network:
    driver: bridge
